name: json_actions
run-name: This is GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: const logger = require('pino')()

logger.info('hello world')

const child = logger.child({ a: 'property' })
child.info('hello child!')
